export default {
  direction: 'ltr',
  margin: 15,
  palette: {
    type: 'light',
    primary: {
      main: '#8bc34a',
    },
    secondary: {
      main: '#fff',
    },
    // mixins:
    // spacing:
    // background: {
    //   default: '#fafafa',
    //   paper: '#fff',
    // },
    // action: {
    //   active: 'rgba(0, 0, 0, 0.54)',
    //   disabled: 'rgba(0, 0, 0, 0.26)',
    //   disabledBackground: 'rgba(0, 0, 0, 0.12)',
    //   hover: 'rgba(0, 0, 0, 0.08)',
    //   hoverOpacity: 0.08,
    //   selected: 'rgba(0, 0, 0, 0.14)',
    // },
    // error: {
    //   contrastText: '#fff',
    //   dark: '#d32f2f',
    //   light: '#e57373',
    //   main: '#f44336',
    // },
    // text: {
    //   disabled: 'rgba(0, 0, 0, 0.38)',
    //   hint: 'rgba(0, 0, 0, 0.38)',
    //   primary: 'rgba(0, 0, 0, 0.87)',
    //   secondary: 'rgba(0, 0, 0, 0.54)',
    // },
    // common: {
    //   black: '#000',
    //   white: '#fff',
    // },
  },
  typography: {
    fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
    fontSize: 14,
    fontWeightLight: 300,
    fontWeightMedium: 500,
    fontWeightRegular: 400,
    button: {
      fontFamily: 'Roboto", "Helvetica", "Arial", sans-serif',
      fontSize: 14,
      fontWeight: 500,
      textTransform: 'uppercase',
    },
    caption: {
      color: 'rgba(0, 0, 0, 0.54)',
      fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
      fontSize: '0.75rem',
      fontWeight: 400,
      lineHeight: '1.375em',
    },
    headline: {
      color: 'rgba(0, 0, 0, 0.87)',
      fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
      fontSize: '1.5rem',
      fontWeight: 400,
      lineHeight: '1.35417em',
    },
    subheading: {
      color: 'rgba(0, 0, 0, 0.87)',
      fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif"',
      fontSize: '1rem',
      fontWeight: 400,
      lineHeight: '1.5em',
    },
    title: {
      color: 'rgba(0, 0, 0, 0.87)',
      fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
      fontSize: '1.3125rem',
      fontWeight: 500,
      lineHeight: '1.16667em',
    },
    body1: {
      color: 'rgba(0, 0, 0, 0.87)',
      fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
      fontSize: '0.875rem',
      fontWeight: 400,
      lineHeight: '1.46429em',
    },
    body2: {
      color: 'rgba(0, 0, 0, 0.87)',
      fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
      fontSize: '0.875rem',
      fontWeight: 500,
      lineHeight: '1.71429em',
    },
    display1: {
      color: 'rgba(0, 0, 0, 0.54)',
      fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
      fontSize: '2.125rem',
      fontWeight: 400,
      lineHeight: '1.20588em',
    },
    display2: {
      color: 'rgba(0, 0, 0, 0.54)',
      fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
      fontSize: '2.8125rem',
      fontWeight: 400,
      lineHeight: '1.13333em',
      marginLeft: '-.02em',
    },
    display3: {
      color: 'rgba(0, 0, 0, 0.54)',
      fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
      fontSize: '3.5rem',
      fontWeight: 400,
      letterSpacing: '-.02em',
      lineHeight: '1.30357em',
      marginLeft: '-.02em',
    },
    display4: {
      color: 'rgba(0, 0, 0, 0.54)',
      fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
      fontSize: '7rem',
      fontWeight: 300,
      letterSpacing: '-.04em',
      lineHeight: '1.14286em',
      marginLeft: '-.04em',
    },
  },
  // transitions: {
  //   duration: {
  //     complex: 375,
  //     enteringScreen: 225,
  //     leavingScreen: 195,
  //     short: 250,
  //     shorter: 200,
  //     shortest: 150,
  //     standard: 300,
  //   },
  //   easing: {
  //     easeIn: 'cubic-bezier(0.4, 0, 1, 1)',
  //     easeInOut: 'cubic-bezier(0.4, 0, 0.2, 1)',
  //     easeOut: 'cubic-bezier(0.0, 0, 0.2, 1)',
  //     sharp: 'cubic-bezier(0.4, 0, 0.6, 1)',
  //   },
  // },
};
